### ISSUE TITLE
Error in ./~/bodymovin/build/player/bodymovin_light.js

### ISSUE THREAD

**Issue by akash-bst** [QubitProducts/react-bodymovin#1]
Using create-react-app. After installing bodymovin. Its shows following error.
(https://www.dropbox.com/s/sgvro4ffpkubwbj/Screenshot%202017-04-04%2016.14.37.png?dl=0)
[screenshot](https://www.dropbox.com/s/84um195n4gkp4xt/Screenshot%202017-04-04%2016.39.44.png?dl=0)

Any help will be appreciable.

**Comment by Olical** [comment]
I tried to look up what character it is actually complaining about but the line mentioned in the error does not exist in my copy. Would you be able to take a look? Maybe the file is corrupted somehow?

**Comment by Olical** [comment]
Okay, I deleted my `node_modules` and fetched it again, apparently there has been an update to bodymovin that broke that file.

```js
}())var bodymovinjs = {};
```

This is not valid JavaScript so it's throwing an error when it tries to parse it. I think bodymovin needs to fix it up stream, or you could explicitly depend on an older version of the dependency.

**Comment by bodymovin** [comment]
found the issue. I will upload a fix tonight.

**Comment by Olical** [comment]
Awesome, probably just in a script concat thing. Add a semi-colon or a new line and it'll be fine.

**Comment by bodymovin** [comment]
Yes, it was exactly that. Fixed. 
Thanks for reporting!

**Comment by Olical** [comment]
I think this should be okay now, as long as it was a patch update for bodymovin? Just reinstall the dependency and it should update.

**Comment by akash-bst** [comment]
Yeah its fixed. We can close this issue 👍
