### ISSUE TITLE
'Loop: true' seems to do nothing

### ISSUE THREAD

**Issue by vincentmvdm** [QubitProducts/react-bodymovin#2]
Hi, 

Thanks for making this wrapper, it is awesome! I was playing around with it, but I could not get my animation to loop. Curious whether I am doing something wrong or if it is a bug:

https://github.com/vincentmvdm/experiment-bodymovin/tree/master/src/components/BodymovinAnimation
http://vincentmvdm.github.io/experiment-bodymovin

Thanks!

**Comment by vincentmvdm** [comment]
Nevermind, I think it is my composition ;)

**Comment by Olical** [comment]
I hope it's all working well for you now! :smile:
