### ISSUE TITLE
Accessing PropTypes via React package deprecated in 15.5

### ISSUE THREAD

**Issue by jurmous** [QubitProducts/react-bodymovin#3]
With React 15.5 this warning is outputted in console:

"Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead."

See top message on following link for more info:
https://facebook.github.io/react/docs/typechecking-with-proptypes.html

**Comment by Olical** [comment]
Oh, I didn't know about this, thanks for the warning.

**Comment by Olical** [comment]
Since I'm not actually getting much value out of PropTypes anyway, I'll just remove the use of it.

**Comment by jurmous** [comment]
Thanks for the quick fix! 😄
