### ISSUE TITLE
npm package 1.0.3 is missing the library

### ISSUE THREAD

**Issue by jurmous** [QubitProducts/react-bodymovin#5]
With npm package 1.0.3 it seems the lib folder is missing and thus the dependency is broken.

**Comment by Olical** [comment]
Oh what!? I'm very sorry, I guess that's because I used `yarn publish`, I thought it was equivalent. Will fix.

**Comment by Olical** [comment]
Looks like it's because of this https://github.com/yarnpkg/yarn/issues/2986

I'll just use npm. Sorry about that.

**Comment by Olical** [comment]
v1.0.4 should be okay

**Comment by jurmous** [comment]
It worked! Thanks again for the quick update! 😄
